### ISSUE TITLE
Openreferences=missing counts and substracts

### ISSUE THREAD

**Issue by Avengium** [Universal-Omega/DynamicPageList3#130]
Hi. I use the feature openreferences =missing to have a short of wanted pages. The feature works well so thanks for that, but something weirds happens.

When i input openreferences and count, i notice the number of items displayed stops before the number in count even when there are more items that can be shown.

Example: Try with this:
https://tuscriaturas.miraheze.org/wiki/Bestiario_del_Hypogripho:P%C3%A1ginasRequeridas/Ayuda

This page has 268 entries when there is no count.
33 when there is count=50
I think maybe is counting 50 and substracting results to 33?

I expect the dpl3 query to return a number of items up to the count.

**Comment by Universal-Omega** [comment]
* #140 should fix this.
