### ISSUE TITLE
ordercollation=latin1_german_ci does not seem to work

### ISSUE THREAD

**Issue by gruniversal** [Universal-Omega/DynamicPageList3#16]
According to https://help.gamepedia.com/Extension:DPL3/Parameters:_Controlling_output_order the parameter `ordercollation=latin1_german_ci` should sort the listing after german collation but it does not seem to change the listing at all.

I am currently trying to sort a list of pages with these params:
`{{#dpl: ordermethod=title|ordercollation=latin1_german_ci|category=xxx}}`

Unfortunately my list still reads:
- Mobilität
- Sandbox
- Ökostrom

Whereas it should be:
- Mobilität
- Ökostrom
- Sandbox

I took a brief look into Query.php and found that `$this->sqlQuery;` does not change when I add `ordercollation=latin1_german_ci`.

So I tried something different and chose utf8_general_ci as collation. This gives me the following error:
`Error 1253: COLLATION 'utf8_general_ci' is not valid for CHARACTER SET 'binary'`

What is the best way to sort my list for german umlauts?

**Comment by Universal-Omega** [comment]
Thank you for reporting this. I will look into it.

**Comment by Universal-Omega** [comment]
Hello, I unfortunately am unable to find the cause of this issue. The only option I can think of is you setting `$wgDBTableOptions = 'ENGINE=InnoDB, DEFAULT CHARSET=utf8';` in LocalSettings.php, then running update.php. However this action can be dangerous, and possibly cause fatal or potential data loss in rare circumstances. Its not a recommended course of action, but the only one I can currently think of. I apologise.
