### ISSUE TITLE
PHP Deprecated error on Mediawiki 1.38.2

### ISSUE THREAD

**Issue by Crystal-Computer-Consulting** [Universal-Omega/DynamicPageList3#196]
**DynamicPageList3 version**: 3.4.6
**MediaWiki version**: 1.38.2
**PHP version**: 7.4.30

**List of steps to reproduce** (step by step, including full links if applicable):
We use DPL on our Main Page. Sometimes we get PHP error text shown at the top of the page that indicates DPL is the cause.

**What happens?**:
We get this error:
Deprecated
": ParserOutput::mCategories public read access deprecated [Called from MediaWiki\Extension\DynamicPageList3\Hooks::endReset in /www-data/wiki.crystalcomputer.com/extensions/DynamicPageList3/includes/Hooks.php at line 552] in "
/www-data/wiki.crystalcomputer.com/includes/debug/MWDebug.php" on line "377

**What should have happened instead?**:
No error

**Browser information, screenshots and other applicable information**:
Happens on all browsers, server is CentOS 8.5 Stream fully patched, serving with Apache 2.4.

**Comment by tim1mike** [comment]
The same config, the same problem:
`PHP Deprecated:  ParserOutput::mCategories public read access deprecated [Called from MediaWiki\Extension\DynamicPageList3\Hooks::endReset in /var/www/mediawiki/extensions/DynamicPageList/includes/Hooks.php at line 530] in /var/www/mediawiki/includes/debug/MWDebug.php on line 377`

**Comment by kristiandelay** [comment]
To fix this update 

replace all instances of mCategories with getCategories()

One example from from DynamicPageListHooks.php
change:
```
if ( self::$createdLinks['resetCategories'] ) {
   $parser->getOutput()->mCategories = self::$fixedCategories;
}

```
to:			
```
if ( self::$createdLinks['resetCategories'] ) {
   $cat = $parser->getOutput()->getCategories();
   $cat = self::$fixedCategories;
 }
```

**Comment by NeilanNaicker** [comment]
Still occurs on Mediawiki 1.38.4.

**Comment by CrystalClearGal** [comment]
This is also an issue on DPL3 v 3.5.0 on MediaWiki 1.39.1 (php 8.0.12) on every page DPL3 is used on, regardless of DPL3 functions used.

**Comment by Universal-Omega** [comment]
I will try and push some fixes for this sometime within the next couple weeks.

**Comment by alistair3149** [comment]
I submitted a PR that should at least fix this issue with `mCategories`.
However, it seems that not every private variables used have a setter method, so I am unsure what can be done on those parts.

**Comment by Universal-Omega** [comment]
> I submitted a PR that should at least fix this issue with `mCategories`. However, it seems that not every private variables used have a setter method, so I am unsure what can be done on those parts.

It might not be possible on all, which is why I haven't fixed it before. But for the extension to continue functioning at all, some functionality from those parts may have to be deprecated and removed when they are completely from MediaWiki, or alternatively a massive hack to make the private variables public and continue using them or alternatively a core patch to add setter methods if it could be approved.

**Comment by Universal-Omega** [comment]
Actually I think it can be done.

**Comment by Universal-Omega** [comment]
Since the methods are defined as references (IE `&getTemplates()`) I think you can set the properties using:
```php
$templates = $parser->getOutput()->getTemplates();
$templates = [];
```
For example.

**Comment by alistair3149** [comment]
That's what I have done in the PR. However, there are only setter methods for categories but not the others.
https://doc.wikimedia.org/mediawiki-core/REL1_39/php/classParserOutput.html

**Comment by Universal-Omega** [comment]
> That's what I have done in the PR. However, there are only setter methods for categories but not the others. https://doc.wikimedia.org/mediawiki-core/REL1_39/php/classParserOutput.html

They don't need setter methods, they have reference methods. you can set using the get methods.

**Comment by Universal-Omega** [comment]
@alistair3149 ^

**Comment by alistair3149** [comment]
Will look into it later in the month, have been busy recently :(
