### ISSUE TITLE
$wgDplSettings['allowUnlimitedResults'] and $wgDplSettings['maxResultCount'] have no influence

### ISSUE THREAD

**Issue by DesignerThan95** [Universal-Omega/DynamicPageList3#20]
I have set both of the variables but the DPL-Statement still only outputs 500 results. Although there should be way more results in that list.

**Comment by Universal-Omega** [comment]
I will try to look into this. Thank you!

**Comment by Universal-Omega** [comment]
Hello, can you please give me an example of the DPL parameters you use?

**Comment by DesignerThan95** [comment]
Sorry for the late reply. Didn't check my mail.

```
wfLoadExtension( 'DynamicPageList3' );
$wgDplSettings['allowUnlimitedCategories'] = true;
$wgDplSettings['allowUnlimitedResults']    = true;
$wgDplSettings['maxResultCount']           = 750;
```

Those are the parameters in the LocalSettings.php file.
I hope that is what you need?

**Comment by Universal-Omega** [comment]
Hello, can you please try with `|count = 750` parameter and see if that works? I apologise for the delayed response.

**Comment by DesignerThan95** [comment]
So finally I took some time and tested the count argument, as I have a workaround in place to show all results I tested it by setting it to 50 but that didn't change anything. All of the result's were shown although the count argument was set to 50.

The workaround I found is, that I changed the config variable "count" to 750 in the file ParametersData.php

**Comment by Universal-Omega** [comment]
* Hello, #53 might fix your issue. I have to do some testing before deployment though.

**Comment by DesignerThan95** [comment]
I have implemented the change you did in the one commit and now it works. Thank's for that!

**Comment by Universal-Omega** [comment]
> I have implemented the change you did in the one commit and now it works. Thank's for that!

You're welcome. Glad it worked for you.
