### ISSUE TITLE
branch REL1_39 missing

### ISSUE THREAD

**Issue by tessus** [Universal-Omega/DynamicPageList3#214]
When updating to mw 1.39, I have noticed that this extension is missing the branch `REL1_39`.

I'm currently using the old branch `REL1_38`, but I think I might have already run into a few issues with it. So I will try using `master` for now.

I am not sure, if you changed the compat policy but I had the impression this extension followed the standard mw release process (with a new branch for every release).

If this is not the case, please let me know and I will always use master from now on.

**Comment by Universal-Omega** [comment]
Sorry for the weird branching here, master is technically latest 1.39 version, or you can use tag releases also, I typically haven't tagged release branches until master stops supporting the versions. This is just to make it easier to maintain release compatibility.

**Comment by tessus** [comment]
ok, in that case I'll just use `master` with the latest version of MediaWiki.

Thanks for your explanation. I am gonna close this. Plese remove the `bug` label. In case you have `info` label, you can use that one or something similar instead.
