### ISSUE TITLE
DPL calls aren't updating automatically?

### ISSUE THREAD

**Issue by NeilanNaicker** [Universal-Omega/DynamicPageList3#24]
I have a page with a very simple DPL call:

{{#dpl:category=Episode|ordermethod=title|order=descending}}

But even when I add new pages to Category:Episode, the above list does not update automatically - until I touch and save the page source - even after accounting for the default caching time of one hour.

**Comment by Universal-Omega** [comment]
It's cached, so no it wold likely need purged first with ?action=purge or saving a new edit. I will look into auto purging cache when updated but that could cause significant performance issues and may not be possible/worthwhile

**Comment by NeilanNaicker** [comment]
Is the intended usage that when a Category is edited, every page with a DPL call that fetches from that category needs to be manually touched as well?

**Comment by Universal-Omega** [comment]
> Is the intended usage that when a Category is edited, every page with a DPL call that fetches from that category needs to be manually touched as well?

No, it just might not update immediately.

**Comment by NeilanNaicker** [comment]
Ah, thanks, understood! I guess that's my query then, how long does the cache take to expire - my understanding was an hour by default, but that has not been my experience - I'm seeing pages still reflect the old data 12 hours later.

**Comment by NeilanNaicker** [comment]
For what it's worth, I've found that my DynamicPageLists WILL update, but only if I explicitly set the cacheperiod=x parameter, even though this is supposed to default to 3600. Perhaps this is a bug?

**Comment by Universal-Omega** [comment]
In that case I'll look into fixing that then. Thanks!

**Comment by Universal-Omega** [comment]
In that case I'll look into fixing that then. Thanks!
