### ISSUE TITLE
Example Code Produces Errors

### ISSUE THREAD

**Issue by jamsoft** [Universal-Omega/DynamicPageList3#266]
**DynamicPageList3 version**: 3.5.2
**MediaWiki version**: 1.41.0
**PHP version**: 7.4.33

I've installed the extension and left it at default settings for initial testing.

I popped the example code into my main page:

```
{{#dpl:
namespace=Extension
|addeditdate=true
|ordermethod=lastedit
|order=descending
|count=10
}}
```

Which just errored with the following message.

**What happens?**:
Extension:DynamicPageList3 (DPL3), version 3.5.2: Error: No selection criteria found! You must use at least one of the following parameters: category, namespace, titlematch, linksto, uses, createdby, modifiedby, lastmodifiedby, or their 'not' variants

If I simplify this to just:

```
{{#dpl:
category=people
}}
```

This works and shows a list of pages in the people category.  But lists the `[Template:Extension DPL]` as missing.

Not entirely sure what to make of this as it seems the extension is installed and working but it's a bit odd that the example code provided produces errors.

**Comment by CrystalClearGal** [comment]
This is not a bug, your syntax is incorrect. 
`namespace=Extension` should be `|namespace=Extension`
In parser function syntax `{{#dpl:}}` **every** parameter must be prefixed with a pipe. You have mixed syntax. 
I can confirm that the usual parser function syntax works just fine in this version.
