### ISSUE TITLE
always show "Template:Extension DPL" in results

### ISSUE THREAD

**Issue by IrishWolf** [Universal-Omega/DynamicPageList3#27]
Hello,

I've got the following problem:
Before the results there is always the bad link to "Template:Extension DPL" (Template:Extension_DPL).

Example (simplest variant):
```
<DPL>
 uses = Template:Teams
</DPL>
```

Result: (the use of <dpl> or {{#dpl doesn't made a difference)
> Template:Extension DPL
> - Page 1
> - ...
> - Page n

I can't get rid of it and the only google-result I've found was this: https://www.mediawiki.org/wiki/Extension_talk:DynamicPageList_(third-party)#Template_name_showing

Server = Ubuntu 18.04
MediaWiki = 1.35.1
PHP = 7.3.27
DB = 10.1.47-MariaDB-0ubuntu0.18.04.1
Extension: DynamicPageList3 3.3.4

**Comment by Universal-Omega** [comment]
While this isn't guaranteed to always work, the https://github.com/Universal-Omega/DynamicPageList3/blob/master/maintenance/createTemplate.php maintenance script is meant to create that.

If that doesn't work simply manually create "Template:Extension_DPL" on your wiki with the contents of `<noinclude>This page was automatically created.  It serves as an anchor page for all '''[[Special:WhatLinksHere/Template:Extension_DPL|invocations]]''' of [https://www.mediawiki.org/wiki/Special:MyLanguage/Extension:DynamicPageList3 Extension:DynamicPageList3].</noinclude>`

**Comment by IrishWolf** [comment]
I've manually created the page with the content and now it looks like it should!

Many thx for the fast answer :)
