### ISSUE TITLE
 Trying to access array offset on value of type null in extensions/DynamicPageList/includes/Parameters.php on line 897'

### ISSUE THREAD

**Issue by Facerafter** [Universal-Omega/DynamicPageList3#31]
We just moved to 1.35 and suddenly get quite a lot in the apache error logging:
` Trying to access array offset on value of type null in extensions/DynamicPageList/includes/Parameters.php on line 897'`

**Comment by designnerd** [comment]
Have you updated the extension? For me this fixed it, though I haven't updated to latest version of MW. See this for reference on same issue:
https://github.com/Universal-Omega/DynamicPageList3/issues/19

**Comment by Facerafter** [comment]
Yeah we have that fix however that error was on line 853, and this is on 897 so I'm guessing it's a different one
