### ISSUE TITLE
Release 3.3.4 is broken

### ISSUE THREAD

**Issue by osnard** [Universal-Omega/DynamicPageList3#45]
Looks like there is a syntax error in the `extension.json` of version 3.3.4:
https://github.com/Universal-Omega/DynamicPageList3/blob/3.3.4/extension.json#L6-L7

Apparently this got fixed shortly after the tagging in https://github.com/Universal-Omega/DynamicPageList3/commit/0c24a3668e2df4ddd62d976886011a91eb57d40f

Could you please create a newer release, or re-tag 3.3.4 to a later commit?

**Comment by Universal-Omega** [comment]
Oh yes I'm sorry. This was broken originally and was fixed on branch. I will retag as 3.3.5. Thank you!

**Comment by Universal-Omega** [comment]
3.3.5 is now tagged.
