### ISSUE TITLE
Setting "allowUnlimitedResults" prevents using "count" option in parser function as a limit

### ISSUE THREAD

**Issue by ineffyble** [Universal-Omega/DynamicPageList3#51]
If you set `$wgDplSettings['allowUnlimitedResults'] = true;` in your settings, the `count` option inside a dpl tag/function gets completely ignored.

This means it can't be used as the equivalent of a `LIMIT X` clause in an SQL statement, and any code that tries to do so will behave unexpectedly.

**Comment by Universal-Omega** [comment]
There is currently a known issue where that configuration, and parameter have zero effect, always leaving that at 500. So does it actually work for you to have a higher limit?

**Comment by Universal-Omega** [comment]
The other issue was fixed. If this still happens for you let me know, but this should be fixed for you as well in recent version of DPL3.
