### ISSUE TITLE
No Results warning not showing

### ISSUE THREAD

**Issue by ineffyble** [Universal-Omega/DynamicPageList3#52]
I'm not entirely sure why, but cases where version 3.3.3 were printing the "No results" warning aren't producing any output under 3.3.5.

**Comment by ineffyble** [comment]
It seems as though adding `debug=3` to the tag parameters shows the expected error. Has there been a change to defaults?

**Comment by Universal-Omega** [comment]
There hasn't been any changes that should effect that but setting the debug to 2 is the correct way it would output. As for config, I suppose that could be useful.

**Comment by Universal-Omega** [comment]
You're welcome to submit a PR to add the configuration option, but I don't intend to do it if you don't. If you do I will merge it though.
