### ISSUE TITLE
Math extension not rendering if DPL contains result

### ISSUE THREAD

**Issue by kitsook** [Universal-Omega/DynamicPageList3#6]
MW: 1.35.0
Math extension: 3.0.0 (b5a8f57)
DPL3 extension: 3.3.4

Example:
```
<math> \displaystyle \frac{59!}{30!} \equiv x \mod{31}</math>
<DPL>
titlematch=Main Page
</DPL>
```

The resulting page is displayed with the markers instead of rendering the math formula:
```
'"`UNIQ--postMath-00000001-QINU`"'

    Main Page
```

If DPL result is empty, the math formula will be rendered correctly, e.g. changing the `titlematch` parameter to a non-existent page:
```
<math> \displaystyle \frac{59!}{30!} \equiv x \mod{31}</math>
<DPL>
titlematch=Main Pagex
</DPL>
```

EDIT: It only happens to math sections that appear **before** DPL on the page.

**Comment by Universal-Omega** [comment]
Thanks for reporting this, I will take a look at it.

**Comment by kitsook** [comment]
Some findings on the issue.

The problem seems to be triggered by calling mediawiki's Parser `parse` function.
https://github.com/Universal-Omega/DynamicPageList3/blob/2cd10c92be1366b71265692604ecc5ccb1b5f9de/classes/Parse.php#L884-L885

Within the `parse` function, the hook `ParserAfterTidy` is triggered. At the same time, in Math extension, the hook seems to only handle the call once.

https://github.com/wikimedia/mediawiki-extensions-Math/blob/6e28bf874312a3068467b84e082d38dd8438a658/src/MathHooks.php#L394-L395

If I comment out the line `self::$tags = [];`, the issue goes away.

I am not familiar with how mediawiki renders pages. Is it this is a bug in Math extension? Or the way that DPL uses parser?

**Comment by kitsook** [comment]
Closing this issue. There is a fix available in Math extension https://phabricator.wikimedia.org/T274316
