### ISSUE TITLE
Scribunto module doesn't work with parser function form

### ISSUE THREAD

**Issue by ittayd** [Universal-Omega/DynamicPageList3#67]
I want to create a hierarchical list of pages, so subpages are indented (using two ** or more) and only the last part of the page name (Bar in Foo/Bar) is shown.

The following works as expected, creating a list of pages with subpages indented (BTW, using ordermethod=title gives an exception)

<pre>
&lt;dpl>
format=,{{#invoke:Helpers|subpage_bullets|page=%PAGE%}} ,&lt;br />,
ordermethod=titlewithoutnamespace
namespace=
&lt;/dpl>
</pre>

(BTW, couldn't use {{NAMESPACE}} as value to namespace either)

But the following does not, subpage names are not split by the slash separator

<pre>
{{#dpl:
format=,\n{{#invoke:Helpers|subpage_bullets|page=%PAGE% }} ,,
| ordermethod=titlewithoutnamespace
| namespace=
}}
</pre>

subpage_bullets is defined as:
<pre>
local p = {} --p stands for package

function p.subpage_bullets( frame )
	local page = frame.args.page
	local parts = mw.text.split( page, "/", true )
    return string.rep("*", #parts) .. " [[" .. page .. "|" ..  parts[#parts] .. "]]"
end

return p
</pre>

One of the things I want to do is to use the output of DPL with the TreeAndMenu extension, and I think I need the parser function form for that.

**Comment by Universal-Omega** [comment]
Note the 2 different format values. Can you attempt to use the exact same for the parser function version, as you do for the working form? If not can you please try updating to the latest version of DPL3, as there has been some changes recently, while not directly targeting these issues, may have had an impact on them.

**Comment by Universal-Omega** [comment]
Please let me know when you try the above mentioned, and I'll look into it. Another thing you could try is another template with the other parser functions in it and attempt to use those templates instead. If it doesn't work, I will reopen this issue. Thanks!

**Comment by Universal-Omega** [comment]
You also may need to use `²{#invoke` but I'm not 100% sure.
