### ISSUE TITLE
MediaWiki 1.35 (LTS) compatibility

### ISSUE THREAD

**Issue by osnard** [Universal-Omega/DynamicPageList3#69]
Hi!

Thank you very much for taking over maintainership of this extension. I noticed, that between versions 3.3.5 an 3.3.6 the MediaWiki core  requirement got bumped from 1.35 to 1.36.

I didn't check all the changes applied in https://github.com/Universal-Omega/DynamicPageList3/pull/57, but are there any other known incompatibilies to MW 1.35 than https://github.com/Universal-Omega/DynamicPageList3/issues/60? It would be awesome if the current LTS release of MediaWiki could be supported. https://github.com/Universal-Omega/DynamicPageList3/issues/60 looks like it was just about some deprecation. Maybe a compatible solution could be found?

**Comment by Universal-Omega** [comment]
There is release branches for this (REL1_35)

**Comment by osnard** [comment]
Sorry to ask again: So you do also actively maintain release branches?

If so, will there be a backport of the fix for https://github.com/Universal-Omega/DynamicPageList3/security/advisories/GHSA-8f24-q75c-jhf4 to `REL1_35`? As far as I could see, this issue was addressed by https://github.com/Universal-Omega/DynamicPageList3/commit/2c04dafb37a14d9ccfe070f53e7f11bbca0156e7. But this commit is not in `REL1_35`.

Or he otherway round: Will users of MediaWiki LTS 1.35 be able to patch the issue or are they advised to set `$wgDplSettings['functionalRichness'] = 0` as mentioned in the security advisory, because they can not use `3.3.6` ?
