### ISSUE TITLE
Disable tracking categories

### ISSUE THREAD

**Issue by gruniversal** [Universal-Omega/DynamicPageList3#86]
I updated from 3.3.3 to 3.3.8 as [advised](https://github.com/Universal-Omega/DynamicPageList3/security/advisories/GHSA-8f24-q75c-jhf4) and now see automatic generated categories beneath my pages: "Pages using DynamicPageList parser function".

I looks like a useful feature in some way but I don't want to show this information to my visitors.

Is there any way to disable these automatic categories?

**Comment by Universal-Omega** [comment]
See https://www.mediawiki.org/wiki/Help:Tracking_categories:

> If the message is a single hyphen-minus (-), then the tracking category is disabled.

Tracking category for this should be `dpl-tag-tracking-category`

**Comment by gruniversal** [comment]
Thanks for you quick answer.

On my site overriding system messages within the database is disabled, since it is recommend for performance reasons: https://www.mediawiki.org/wiki/Manual:$wgUseDatabaseMessages

But I was able to hide the annoying entry by creating a category page with __HIDDENCAT__ as described in the link you posted.

So thanks anyway :)
