### ISSUE TITLE
DPL3 does not respect $wgAllowDisplayTitle and show the set DisplayTitle in result sets

### ISSUE THREAD

**Issue by designnerd** [Universal-Omega/DynamicPageList3#9]
All recent versions of DPL3, on MW 1.33, 1.34, 1.35, DPL3 will not respect a page's set display title when  $wgAllowDisplayTitle is set. E.g., If a page is entitled "IPod" and has content {{DISPLAYTITLE:iPod}} and it is included in the DPL3 output results, the page name will be displayed as "IPod" rather than being displayed as set in the {{DISPLAYTITLE}} magic word as occurs in categories and other MediaWiki pages. It would be awesome if DPL3 could recognize and display DisplayTitle in result sets if $wgAllowDisplayTitle is set. :)

**Comment by Universal-Omega** [comment]
I'll look into methods of implementing this, however no promises I'll succeed in making this possible.

**Comment by designnerd** [comment]
Thanks for looking into it, and no worries, if it requires too much of a code overhaul it wouldn't be worth it. 
I just really really appreciated you updating the extension to make compatible with 1.35, so not having this is not super important. :)

**Comment by Universal-Omega** [comment]
I apologize, but I looked into this, and while it is possible, I think it's not worth it and could overall diminish performance. Therefore I unfortunately can't do this as it could cause issues, however if I find a better way into the future I will do it then. Thank you!

**Comment by designnerd** [comment]
No worries and no apology needed. I totally understand! Thanks for taking a look Universal-Omega!
